# Generated by Django 4.1.3 on 2022-11-17 21:26

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dairy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('content', django_quill.fields.QuillField(default='ici')),
                ('post_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Diary',
                'verbose_name_plural': 'Diaries',
            },
        ),
    ]
